// import NavBar from '@/components/NavBar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ContextProvider } from '@/components/ContextProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen justify-center bg-gray-100 text-black">
          <div className="container">     
            <ContextProvider>
              {/* <NavBar /> */}
              {children}
            </ContextProvider>
          </div>
        </main>
      </body>
    </html>
  )
}
